/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119615-gf414038779-20250520"
#endif /* AVUTIL_FFVERSION_H */
